language: python

python:
  - "2.7"
  # - "3.4"

addons:
  apt:
    packages:
      - build-essential
      - libatlas-base-dev

sudo: false

install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  - conda install numpy cython scipy pytest scikit-learn
  - python setup.py install
  - source deactivate

script:
  - pwd
  - source activate test-environment
  - cd tsne/tests
  - py.test -s -vv
